FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/SmtpToMessageSender/SmtpToMessageSender.csproj", "src/SmtpToMessageSender/"]
RUN dotnet restore "./src/SmtpToMessageSender/SmtpToMessageSender.csproj"
COPY . .
WORKDIR "/src/src/SmtpToMessageSender"
RUN dotnet build "./SmtpToMessageSender.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./SmtpToMessageSender.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SmtpToMessageSender.dll"]
